name: Build Windows EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install flask pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --onefile backend/app.py --name "SKDian Library"

      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v3
        with:
          name: SKDianLibrary-Windows
          path: dist/"SKDian Library".exe