name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build APK
        run: |
          cd frontend
          npx expo build:android -t apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: LibraryApp-Android
          path: frontend/dist/*.apk`
